### ISSUE TITLE
GM_getValue is not defined, firefox, greasemonkey

### ISSUE THREAD

**Issue by zpalmtree** [akiirui/userscript#1]
Hello,
I installed this extension in Firefox, along with https://aur.archlinux.org/packages/mpv-handler-git/

The icon to load the video into mpv does not appear to be appearing, and in addition I see this logged in my browser console on a youtube video:

```
Script error in [Greasemonkey script play-with-mpv-handler/Play with mpv; version 2021.01.01]:
ReferenceError: GM_getValue is not defined
```

Since `// @grant               GM_getValue` is included in the userscript definition, I'm not sure why this is erroring.

**Comment by akiirui** [comment]
Yep, I found what's wrong.

Greasemonkey has changed GM API since v4.0.

New GM API looks like `GM.getValue`, but Tampermonkey & Violentmonkey still using `GM_getValue`.
(I haven't test this script at Greasemonkey...)

Let me see how to compatible with Greasemonkey.

**Comment by akiirui** [comment]
Emm, I think I can't compatible this script with Greasemonkey v4.0+ 😅😅😅.

1. A important library `GM_config` isn't fully compatible with v4.0+. 

    Such as "Video Quality" setting is save to localStorage (per sites, and it will reset after clear cookies) instead of save to userscript manager database.

    For better experience, I want these settings save to script manager database.

2. Some userscript manager (such Tampermonkey) not supported `GM.*` API.

I will mark this script not compatible with Greasemonkey v4.0+, and recommend you try Violentmonkey (compatible `GM_*` and `GM.*`) or Tampermonkey (compatible `GM_*` only) on Firefox.

Thanks.

**Comment by akiirui** [comment]
Or I compatible main userscript with Greasemonkey v4.0+, but library `GM_config` will save settings to localStorage (I will add some description about this to README).

**Comment by zpalmtree** [comment]
I installed tampermonkey and it's working fine with that. Thanks!
