### ISSUE TITLE
allow run at any site with a show hide toggle for current site

### ISSUE THREAD

**Issue by 404b** [akiirui/userscript#12]
you can ` // @match  *://*/*` to achieve this
and a gm property to save button hidden on disabled sites.

**Comment by akiirui** [comment]
I considered this method, but it is dirty.

All pages will show the icons in the bottom left corner, and users need to go one by one to hide them, which is troublesome.

The current method is only show the icon on the video/playlist pages. But it needs to be added manually.

I will add a global settings page later to enable the script for some sites.

**Comment by 404b** [comment]
> I considered this method, but it is dirty.
> 
> All pages will show the icons in the bottom left corner, and users need to go one by one to hide them, which is troublesome.
> 
> The current method is only show the icon on the video/playlist pages. But it needs to be added manually.
> 
> I prefer to keep the script simple, stupid. If you need more supported sites, let me know.

Dirty yes, for me simple button no hurt me, yt-dlp supports plethora of sites so if you want to enable one by one it will be long userscript. But ultimately your choice. Good job

**Comment by akiirui** [comment]
Maybe I can write a script to parse yt-dlp sites regex and add to this script.

Match all of the sites and check by these regex rules.

Then, K.I.S.S. for users and support all sites from yt-dlp.

**Comment by akiirui** [comment]
Maybe I can write a script to parse yt-dlp sites regex and add to this script.

Match all of the sites and check by these regex patterns.

Then, K.I.S.S. for users and support all sites from yt-dlp.

**Comment by 404b** [comment]
> Maybe I can write a script to parse yt-dlp sites regex and add to this script.
> 
> Match all of the sites and check by these regex patterns.
> 
> Then, K.I.S.S. for users and support all sites from yt-dlp.

Yeah definitely 👍  Btw can i use a small chunk of your code on my userscript?

**Comment by 404b** [comment]
> Of course, feel free to use it. The script is open-sourced under the MIT license.

thanks
