### ISSUE TITLE
Add mpv config option for Video Quality & Video Codec

### ISSUE THREAD

**Issue by xd003** [akiirui/userscript#16]
Really great work with this userscript, appreciate it. One thing i noticed that the play with mpv settings ( by tapping the mpv icon on bottom left )  gives video quality and video codec option. In that, can you please add a dropdown option to use the mpv config for video quality and codec setting ?
I am not really sure if the video quality and codec option i have defined in my mpv.conf will override the options set as default in play with mpv settings, if that's the case, then well and good, nothing to be done

**Comment by akiirui** [comment]
> In that, can you please add a dropdown option to use the mpv config for video quality and codec setting?

Do you want select quality and codec **per video** or **per site**?

Add dropdown menu looks ugly and may obscure more elements on the page.

> I am not really sure if the video quality and codec option i have defined in my mpv.conf will override the options set as default in play with mpv settings

It is passing command line options to mpv. Command line options has higher priority than the options in mpv.conf.

**Comment by akiirui** [comment]
Maybe I should change these two options to `default`?

**Comment by xd003** [comment]
> Maybe I should change these two options to `default`?

yes  exactly, that would be much better/clearer to user

**Comment by akiirui** [comment]
Done, thanks for your suggestions.
