### ISSUE TITLE
Please allow users to custom add websites.

### ISSUE THREAD

**Issue by zhouxinghong** [akiirui/userscript#17]
Please allow users to custom add websites.
Thank you very much! 👍😜

**Comment by akiirui** [comment]
Done https://github.com/akiirui/userscript/commit/68edc7139173e8f089310763ba789e93a8bff827

**Comment by akiirui** [comment]
Revert at https://github.com/akiirui/userscript/commit/0a07dfb6816f3e4381cda12780a651346b0aaab9
Because GreasyFork mark this script as adult and limit it. I will push another version to SleazyFork.

**Comment by zhouxinghong** [comment]
Thank you very much! 🍦😜.
Is it possible to upgrade the script to allow users to customize adding favorite sites? This would allow you to greatly reduce maintenance difficulties. 👍😜

**Comment by akiirui** [comment]
1. If allow add custom site, we should match all sites in script like `*://*/*`, it's dangerous and dirty.

2. Simply adding a custom site will cause the play button to appear on all pages of the site, it obscures the content of the page in many unnecessary places.

So I won't implement it.

**Comment by zhouxinghong** [comment]
Can you provide two versions:
1. Ordinary version
2, Enhanced version (support for user-defined add site), so that users can install the correct version according to different needs, as for the danger and dirty by the user to decide.

**Comment by zhouxinghong** [comment]
If the above design idea is adopted, then the flexibility of the whole extension and the available scenarios will be greatly enhanced.

**Comment by zhouxinghong** [comment]
`If allow add custom site, we should match all sites in script like *://*/*, it's dangerous and dirty.`
Enhanced version (support for users to customize the addition of sites), so that users can be based on different needs to install the correct version, as for the danger and dirty by the user to decide. This version allows the user to customize the configuration of the website on the local computer.

`Simply adding a custom site will cause the play button to appear on all pages of the site, it obscures the content of the page in many unnecessary places.`
If you don't want the page content to be obscured by buttons, just disable the script and refresh the page.

**Comment by akiirui** [comment]
> Can you provide two versions

Sorry, I won't provide. Contributions are welcome.

And NSFW version is here [play-with-mpv-nsfw](https://sleazyfork.org/scripts/494748-play-with-mpv-nsfw)

Done.

**Comment by zhouxinghong** [comment]
Does this version allow users to customize the sites they add?

**Comment by akiirui** [comment]
No, I'm not planning to provide that version.

**Comment by zhouxinghong** [comment]
So there are 1000 sites to add and you need to maintain 1000 sites

**Comment by akiirui** [comment]
> So there are 1000 sites to add and you need to maintain 1000 sites

**Contributions are welcome.** 

Anyone can contribute to this, to support a new site is just a simple two line regex match.
Or create a userscript to do what you want.

I'm just an open source enthusiast, and the script was initially for personal use only. I have no ability or obligation to fulfill every user's wishes.

Thanks.
