### ISSUE TITLE
Video quality don't work on bilibili.com

### ISSUE THREAD

**Issue by ieeyaY** [akiirui/userscript#18]
I set the preferred video quality on the page button to 2160p, but the resolution is 480p in mpv. I also tried to copy link and modify the option in the link, then open it on the new page, but still 480p.
This option works well on YouTube and other websites.

**Comment by akiirui** [comment]
bilibili limits video quality for guest users, trying to pass cookies.

**Comment by ieeyaY** [comment]
I exported cookies to the folder with chrome extension "Get cookies.txt LOCALLY", and then it did work. Thank you!
