### ISSUE TITLE
[bug] Play with MPV doesn't load since last update

### ISSUE THREAD

**Issue by bagnacauda** [akiirui/userscript#19]
I see you added a css`, I'm not familiar with prettier but that causes the userscript to fail to load. Reverting to the previous version works

Console output: 
ReferenceError: css is not defined
    VM9j320amqsx moz-extension://dbe8dcf5-ec3f-4652-bd82-c26f4893e6dd/ Play with MPV.user.js#2:1005
    VM9j320amqsx moz-extension://dbe8dcf5-ec3f-4652-bd82-c26f4893e6dd/ Play with MPV.user.js#2:1334
    VM9j320amqsx moz-extension://dbe8dcf5-ec3f-4652-bd82-c26f4893e6dd/ Play with MPV.user.js#2:1334
    Bt moz-extension://dbe8dcf5-ec3f-4652-bd82-c26f4893e6dd/sandbox/injected-web.js:1
    <anonymous> moz-extension://dbe8dcf5-ec3f-4652-bd82-c26f4893e6dd/ Play with MPV.user.js#2:1
Play with MPV.user.js:1334:31
    VM9j320amqsx moz-extension://dbe8dcf5-ec3f-4652-bd82-c26f4893e6dd/ Play with MPV.user.js#2:1334
    Bt moz-extension://dbe8dcf5-ec3f-4652-bd82-c26f4893e6dd/sandbox/injected-web.js:1
    <anonymous> moz-extension://dbe8dcf5-ec3f-4652-bd82-c26f4893e6dd/ Play with MPV.user.js#2:1
    Gt moz-extension://dbe8dcf5-ec3f-4652-bd82-c26f4893e6dd/injected.js:1
    Jt moz-extension://dbe8dcf5-ec3f-4652-bd82-c26f4893e6dd/injected.js:1

**Comment by akiirui** [comment]
what script manager are you using？

**Comment by akiirui** [comment]
I revert that changes, thanks.
https://github.com/akiirui/userscript/commit/525647f77410c0de49ef5e22c3e6a606e6e3d818
