### ISSUE TITLE
play-with-mpv-handler: Support twitch.tv and show icon in thumbnail

### ISSUE THREAD

**Issue by Neomanbeta** [akiirui/userscript#2]
现在启动mpv的方式是打开视频才能在右下角点击图标唤出mpv，不知道能否借鉴一下youtube links脚本的方式（这是个下载youtube视频和音频的脚本），在缩略图上显示小图标，从而不用进入详情页，直接点击缩略图上的图标就能启动mpv。
PS:youtube-dl是支持twitch直播和clips的，不知道能不能顺便也支持一下。

**Comment by akiirui** [comment]
可以是可以，不过每一个网站的元素和CSS不一样，适配需要的工作量太大了（
欢迎 PR。

**Comment by akiirui** [comment]
twitch 和 clips 会尽快添加支持。

前一个问题在 https://greasyfork.org/en/scripts/416271-play-with-mpv/discussions/74657 也有过建议。

**Comment by akiirui** [comment]
至于在缩略图上显示 `play-with-mpv` 的图标。 

这个其实是解决 GreasyFork 上那一个建议并且不影响浏览器右键菜单比较好的解决方案。

但是在**哔哩哔哩**这样的视频站上。右侧排行榜的视频列表有的没有缩略图，这样就不会工作。并且需要遍历并修改整个页面的元素，可能会造成性能问题。

想找一个完美的方案解决这问题（

**Comment by Neomanbeta** [comment]
嗯，我说的那个也只是个建议，因为youtube links在后来的FF版本里会造成页面响应缓慢和卡顿（很奇怪为什么之前的版本不会），其实主要是想不进入详情页就可以选择用mpv播放而已。

**Comment by akiirui** [comment]
你好，你说的那一个 clips 是什么视频站呢？我没找到（

**Comment by akiirui** [comment]
> 嗯，我说的那个也只是个建议，因为youtube links在后来的FF版本里会造成页面响应缓慢和卡顿（很奇怪为什么之前的版本不会），其实主要是想不进入详情页就可以选择用mpv播放而已。

其实这个问题我自从 GreasyFork 那边提过之后，我大致有一个想法。

在支持的网站任何页面都显示 `play-with-mpv` 图标，然后拖动 URL 至这个图标上就调用 `mpv-handler` 播放这个 URL。

**Comment by akiirui** [comment]
`twitch.tv` 的相关支持已在 https://github.com/akiirui/userscript/commit/bf53a31d9a78a22bf2a0165e5fc737b7ccb75426 中添加

**Comment by Neomanbeta** [comment]
clips指的就是twitch频道里保存的直播时候截取的片段，这个不是单独的网站。
这个没有那么的重要。

**Comment by akiirui** [comment]
> clips指的就是twitch频道里保存的直播时候截取的片段，这个不是单独的网站。
> 这个没有那么的重要。

有具体的 URL 么。。

**Comment by Neomanbeta** [comment]
https://clips.twitch.tv/embed?clip=SmallLitigiousLeg4Head&parent=twitch.tv&tt_content=video_thumbnail&tt_medium=twitch_home
比如这个，clips都非常短，就几十秒。

**Comment by akiirui** [comment]
> https://clips.twitch.tv/embed?clip=SmallLitigiousLeg4Head&parent=twitch.tv&tt_content=video_thumbnail&tt_medium=twitch_home
> 比如这个，clips都非常短，就几十秒。

emm。如果 URL 格式是 `https://www.twitch.tv/USERNAME/clip/CLIPNAME` 的话已经支持了。
但是 `https:/clips.twitch.tv/*` 这种的不支持。

后面这种 URL 格式常用么？

**Comment by Neomanbeta** [comment]
从频道点进去的clips的确已经支持了，我上面贴的那个链接是首页推荐的clips，这种地址还不被支持，常用不常用。。。这个我就不好说了。

**Comment by akiirui** [comment]
> 从频道点进去的clips的确已经支持了，我上面贴的那个链接是首页推荐的clips，这种地址还不被支持，常用不常用。。。这个我就不好说了。

恩，既然有用到的地方我就把它加上去。

**Comment by akiirui** [comment]
我在首页推荐没找到 `clips.twitch.tv` 相关的 URL。。 似乎 `https://clips.twitch.tv/embed?` 这种 URL 是用于站外播放的？

**Comment by Neomanbeta** [comment]
> 
> 
> 我在首页推荐没找到 `clips.twitch.tv` 相关的 URL。。 似乎 `https://clips.twitch.tv/embed?` 这种 URL 是用于站外播放的？

你需要登录了账号，关注了主播，才会在首页给你推荐他们的clips，你首页没有可能是你没有登录？或者你登录了没有关注任何人？或者你关注的人并不存在clips？这些情况都有可能。

**Comment by akiirui** [comment]
`clips.twitch.tv` 相关支持已在 https://github.com/akiirui/userscript/commit/a638a9bdaedcfab60b3a8db20a9a2677ae9c3c85 中添加。

预览图中添加图标调用 mpv-handler 的功能决定暂不添加，等想到更好的方法后再解决这个问题。
