### ISSUE TITLE
Settings window is just a white box, mpvnet questions

### ISSUE THREAD

**Issue by Kamek437** [akiirui/userscript#23]
On windows when I press the little gear icon above the mpv icon a little white box opens which I assume is the settings menu, but nothing is displayed it's just a white box that stays there. I do have some other extensions in use but as of yet have not been able to narrow it down. Also, I find that using mpvnet is a far better option for most people in that, titles on the window and in general player ui is far better so I went with that, and all seems mostly ok so you might recommend that. The command prompt that pops up after the play icon is pressed says some stuff about hardware acceleration errors and it try to play 4k stuff which I can't handle on this machine so I need to be able to get to the settings to change that and I can't. Any help appreciated, logs and screenshots available if you need. I really like the idea of this project but the settings window not showing up is making it hard to use.

**Comment by Kamek437** [comment]
That got it guys thank you so much!

**Comment by Kamek437** [comment]
Awesome! mpv.net works just fine as it's just a customized mpv ui in lua etc. I was just thinking if you guys wanted something that has a bit more ui bits on the mpv side maybe try it if you want, I think it looks really nice. Keep up the good work this is a really cool project!

**Comment by akiirui** [comment]
Did userscript v2024.08.11 fix the settings window white box on YouTube issue for you?

**Comment by Kamek437** [comment]
Yep it did thanks guys!

**Comment by akiirui** [comment]
Fine, I will add an alternative **mpv.net** to the README.
Done.
