### ISSUE TITLE
Bilibili是不是不能播放番剧和电影这类视频？

### ISSUE THREAD

**Issue by zanewayne78** [akiirui/userscript#25]
只能用脚本播放普通视频吗？能让番剧，电影，电视剧都能用MPV就好了

**Comment by akiirui** [comment]
我试了一下，番剧是可以的。
请分别列出 番剧，电影，电视剧的链接。我添加到正则匹配里。

**Comment by zanewayne78** [comment]
番剧https://www.bilibili.com/bangumi/play/ss33378
电影https://www.bilibili.com/bangumi/play/ss46299
电视剧https://www.bilibili.com/bangumi/play/ep832867
不知道这些要会员的视频能不能放

**Comment by akiirui** [comment]
需要会员的视频传递 Cookies 就可以了。

**Comment by akiirui** [comment]
Done https://github.com/akiirui/userscript/commit/8d72dfae19ca0ee7e96100fa35166697ac619b91
