### ISSUE TITLE
twitch is not working anymore

### ISSUE THREAD

**Issue by Neomanbeta** [akiirui/userscript#4]
script version 2021.04.24
tested on win10 and win7 with firefox 88 with mpv and youtube-dl updated to the latest version.

**Comment by akiirui** [comment]
Do you have any other information? (mpv-handler output or where functions are not working)

Tested on Linux and Windows 10, Firefox 88, mpv-handler 0.1.8, youtube-dl 2021.04.26.
mpv-handler works fine.

**Comment by Neomanbeta** [comment]
Playing: https://www.twitch.tv/matimi0|Best
[ytdl_hook] ERROR: matimi0|best does not exist
[ytdl_hook] youtube-dl failed: unexpected error occurred
Failed to recognize file format.

Exiting... (Errors when loading file)
Player exited with error or termination signal

**Comment by akiirui** [comment]
> Playing: [https://www.twitch.tv/matimi0|Best](https://www.twitch.tv/matimi0%7CBest)
> [ytdl_hook] ERROR: matimi0|best does not exist
> [ytdl_hook] youtube-dl failed: unexpected error occurred
> Failed to recognize file format.
> 
> Exiting... (Errors when loading file)
> Player exited with error or termination signal

Emm, Are you sure your userscript and mpv-handler are both latest version?

This output told me, your userscript is out of date.

**Comment by Neomanbeta** [comment]
yeah, i'm pretty sure it's the latest version, otherwise a popup windows will show telling me that i have to update the handler right?
md5 of the handler.exe : D53B3AF06D2E22D00704C8BA515216F9

**Comment by Neomanbeta** [comment]
Playing: https://www.twitch.tv/matimi0
[ytdl_hook] ERROR: Unable to download JSON metadata: <urlopen error [SSL: CERTIFICATE_VERITY_FAILED] certificate verify faild <ssl.c:600>> <caused by URLERROR<SSLError<1,'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed <_ssl.c:600>'>,>>
[ytdl_hook] youtube-dl failed: unexpected error occurred
Failed to regognize file format.

Exiting... (Errors when loading file)
Player exited with error or termination signal

This is the correct output message from win7.
i got win10 working after i reinstalled the script and the handler again, but no luck with win7.

**Comment by akiirui** [comment]
> i got win10 working after i reinstalled the script and the handler again, but no luck with win7.

This output shows youtube-dl cannot open URL, because ytdl uses out of date SSL Certificates.

You can check https://github.com/ytdl-org/youtube-dl/issues/7309#issuecomment-172354527 to solve this problem.

**Comment by Neomanbeta** [comment]
if it's a youtube-dl related problem then i will close this issue, thanks for the help. I tried the above mentioned method, but i could not find any twitch certs in my system, i guess i will wait for an update of youtube-dl, hope that will solve my problem.
