### ISSUE TITLE
Could you add a option to open without settings?

### ISSUE THREAD

**Issue by angelss197200** [akiirui/userscript#5]
i cant open mpv from the browser but i can in the console with xdg-open and without?quality=720p&cookies=no
i think this is the best option to people that have setup mpv an youtube-dl

**Comment by akiirui** [comment]
Can't open mpv from the browser?
Can you show the error information in the terminal? I think you upgrade script, but you aren't upgrade mpv-handler.
I have changed URL options format in the new version, So old version mpv-handler is not compatible with new script.

And the default options is `quality=best&cookies=no`.
The `quality=best` same as youtube-dl default behavior.

**Comment by angelss197200** [comment]
I installed 3 days ago the aur version
runing this

xdg-open mpv://aHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g/dj1sTGN3R0RRUFotcw==/?quality=best&cookies=no    

i get this
                          
>[1] 2794
zsh: no matches found: mpv://aHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g/dj1sTGN3R0RRUFotcw==/?quality=best
[1]  + exit 1     xdg-open

If i put it between quotes it works
if i delete the "?quality=best&cookies=no" it works
it doenst work in the browser

**Comment by akiirui** [comment]
> If i put it between quotes it works
> if i delete the "?quality=best&cookies=no" it works

Yep, that is need quotes, because this URL has `?` and `&`

> it doenst work in the browser

Can you show me the error message when you open in the browser script? It's will open a terminal, and run the mpv-handler in it.
