### ISSUE TITLE
Do not work me

### ISSUE THREAD

**Issue by foxrus** [akiirui/userscript#6]
I installed according to the instructions, but when I click play with mpv, I get an error - No such file or directory (os error 2)
What am I doing wrong?

**Comment by foxrus** [comment]
Ubuntu 20.04

**Comment by akiirui** [comment]
the `mpv-handler.toml` should be placed at ~/.config/mpv/mpv-handler.toml

Check https://github.com/akiirui/mpv-handler/blob/main/README.md for more details.

**Comment by akiirui** [comment]
There is no reply for too long, close this issue.

If you still have this problem, please reopen it.
